source "https://rubygems.org"
ruby File.read(".ruby-version").chomp

gem "govwifi_eapoltest", git: "https://github.com/GovWifi/govwifi_eapoltest.git"
gem "json"
gem "mysql2"
gem "rspec"
gem "rubocop-govuk"
gem "sequel", "~> 5.99"
