groups:
- name: tester
  jobs:
  - test
- name: self-update
  jobs:
  - self-update

resource_types:
- name: pull-request
  type: registry-image
  source:
    repository: teliaoss/github-pr-resource

resources:
  - name: tech-ops
    type: git
    source:
      uri: https://github.com/alphagov/tech-ops.git

  - name: govwifi-acceptance-tests
    type: git
    source:
      uri: https://github.com/alphagov/govwifi-acceptance-tests.git

  - name: pull-request
    type: pull-request
    check_every: 1m
    source:
      repository: alphagov/govwifi-acceptance-tests
      access_token: ((github-access-token))

  - name: runner
    # See https://github.com/alphagov/govwifi-concourse-runner for a reference dockerfile
    # readonly_private_ecr_repo_url is provided by the hosted Concourse
    type: docker-image
    source:
      repository: "((readonly_private_ecr_repo_url))"
      tag: concourse-runner-latest

  - name: authentication-api
    type: git
    source:
      uri: "https://github.com/alphagov/govwifi-authentication-api.git"
      branch: master
  
  - name: logging-api
    type: git
    source:
      uri: "https://github.com/alphagov/govwifi-logging-api.git"
      branch: master
  
  - name: frontend
    type: git
    source:
      uri: "https://github.com/alphagov/govwifi-frontend.git"
      branch: master

update-status-commands:
  update-status-base: &update-status-base
    put: update-status
    resource: pull-request
    get_params:
      skip_download: true

  update-status-params-base: &update-status-params-base
    path: src
    context: 'pr'

  update-status-pending: &update-status-pending
    <<: *update-status-base
    params:
      <<: *update-status-params-base
      status: pending

  update-status-failure: &update-status-failure
    <<: *update-status-base
    params:
      <<: *update-status-params-base
      status: failure

  update-status-success: &update-status-success
    <<: *update-status-base
    params:
      <<: *update-status-params-base
      status: success

jobs:
  - name: self-update
    serial: true
    plan:
    - get: tech-ops
      params:
        submodules: none
    - get: govwifi-acceptance-tests
      trigger: true
    - task: set-pipelines
      file: tech-ops/ci/tasks/self-updating-pipeline.yaml
      input_mapping: {repository: govwifi-acceptance-tests}
      params:
        CONCOURSE_TEAM: govwifi
        CONCOURSE_PASSWORD: ((readonly_local_user_password))
        PIPELINE_PATH: ci/pipelines/pr.yml
        PIPELINE_NAME: acceptance-tests-pr

  - name: test
    interruptible: true
    # force people to use new git commits to rerun PRs
    disable_manual_trigger: true
    plan:
      - aggregate:
        - do:
          - get: src
            resource: pull-request
            trigger: true
            version: every
          - <<: *update-status-pending
          - get: frontend
          - get: authentication-api
          - get: logging-api
        - get: runner

      - task: test
        privileged: true
        image: runner
        file: src/ci/tasks/test.yml

    on_failure:
      do:
        - <<: *update-status-failure
    on_success:
      do:
        - <<: *update-status-success
