version: 2
updates:
- package-ecosystem: bundler
  directory: "/acceptance_tests"
  schedule:
    interval: daily
    time: "03:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: sequel
    versions:
    - 5.40.0
    - 5.41.0
    - 5.42.0
- package-ecosystem: docker
  directory: "/acceptance_tests"
  schedule:
    interval: daily
    time: "03:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: ruby
    versions:
    - 3.0.0.pre.alpine
