version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - echo "AWS_REGION is $AWS_REGION "
      - echo "$DOCKER_HUB_AUTHTOKEN_ENV" | docker login -u $(echo $DOCKER_HUB_USERNAME_ENV) --password-stdin
  build:
    commands:
      - echo Build started on `date`
      - make test
  post_build:
    commands:
      - echo Done at `date`

