version: '3.4'

services:
  govwifi-sessions-db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: testpassword
      MYSQL_DATABASE: govwifi_local
    healthcheck:
      test: "mysql --user=root --password=testpassword -e 'SELECT 1'"

  govwifi-user-details-db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: testpassword
      MYSQL_DATABASE: govwifi_local
    healthcheck:
      test: "mysql --user=root --password=testpassword -e 'SELECT 1'"


  govwifi-fake-s3:
    build:
      context: fake-s3

  govwifi-frontend-local:
    build:
      context: .frontend
    depends_on:
      - govwifi-fake-s3
      - govwifi-authentication-api-local
      - govwifi-logging-api-local
    environment:
      AUTHORISATION_API_BASE_URL: "http://govwifi-authentication-api-local:8080"
      LOGGING_API_BASE_URL: "http://govwifi-logging-api-local:8080"
      RADIUS_CONFIG_WHITELIST_URL: "http://govwifi-fake-s3:8080/clients.conf"
      HEALTH_CHECK_RADIUS_KEY: RrPTmh8s9NZFenAFx2kG
      HEALTH_CHECK_SSID: GovWifi
      HEALTH_CHECK_IDENTITY: DSLPR
      HEALTH_CHECK_PASSWORD: SharpRegainDetailed
      RADIUSD_PARAMS: "-X"
      CERT_STORE_URL: "http://govwifi-fake-s3:8080"
    ports:
      - 9090:80

  govwifi-authentication-api-local:
    build:
      context: .authentication-api
      args:
        BUNDLE_INSTALL_CMD: bundle install --without test --no-cache --jobs 8
    depends_on:
      - govwifi-user-details-db
    environment:
      DB_HOSTNAME: govwifi-user-details-db
      DB_USER: root
      DB_PASS: testpassword
      DB_NAME: govwifi_local

  govwifi-logging-api-local:
    build:
      context: .logging-api
      args:
        BUNDLE_INSTALL_CMD: bundle install --without test --no-cache --jobs 8
    depends_on:
      - govwifi-sessions-db
    environment:
      DB_HOSTNAME: govwifi-sessions-db
      DB_USER: root
      DB_PASS: testpassword
      DB_NAME: govwifi_local
      USER_DB_NAME: govwifi_local
      USER_DB_PASS: testpassword
      USER_DB_USER: root
      USER_DB_HOSTNAME: govwifi-user-details-db

  govwifi-test:
    build:
      context: acceptance_tests
    depends_on:
      - govwifi-sessions-db
      - govwifi-frontend-local
    environment:
      DB_HOSTNAME: govwifi-sessions-db
      DB_NAME: govwifi_local
      DB_USER: root
      DB_PASS: testpassword
      USER_DB_NAME: govwifi_local
      USER_DB_PASS: testpassword
      USER_DB_USER: root
      USER_DB_HOSTNAME: govwifi-user-details-db
      FRONTEND_CONTAINER: govwifi-frontend-local
      RADIUS_KEY: testingradiussecret
