version: '3.4'

services:
  sessions-db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: testpassword
      MYSQL_DATABASE: govwifi_local
    healthcheck:
      test: "mysql --user=root --password=testpassword -e 'SELECT 1'"

  user-details-db:
    image: mysql:8.0
    command: "--default-authentication-plugin=mysql_native_password"
    environment:
      MYSQL_ROOT_PASSWORD: testpassword
      MYSQL_DATABASE: govwifi_local
    healthcheck:
      test: "mysql --user=root --password=testpassword -e 'SELECT 1'"

  fake-s3:
    image: localstack/localstack
    ports:
      - "4572:4572"
      - "8080:8080"
    environment:
      - SERVICES=s3
      - DOCKER_HOST=unix:///var/run/docker.sock
      - DEFAULT_REGION=eu-west-1
      - AWS_ACCESS_KEY_ID=testkey
      - AWS_SECRET_ACCESS_KEY=testsecret
    volumes:
      - ./fake-s3:/tmp/localstack
      - /var/run/docker.sock:/var/run/docker.sock
      - ./fake-s3/localstack-init:/docker-entrypoint-initaws.d

  frontend-local:
    build:
      context: .frontend
    depends_on:
      - authentication-api-local
      - logging-api-local
    environment:
      AUTHORISATION_API_BASE_URL: "http://authentication-api-local:8080"
      LOGGING_API_BASE_URL: "http://logging-api-local:8080"
      RADIUS_CONFIG_WHITELIST_URL: "http://fake-s3:8080/clients.conf"
      HEALTH_CHECK_RADIUS_KEY: RrPTmh8s9NZFenAFx2kG
      HEALTH_CHECK_SSID: GovWifi
      HEALTH_CHECK_IDENTITY: DSLPR
      HEALTH_CHECK_PASSWORD: SharpRegainDetailed
      RADIUSD_PARAMS: "-X"
    volumes:
      - raddb-certs:/etc/raddb/certs 

  frontend-raddb-local:
    build:
      context: .frontend
      dockerfile: Dockerfile.raddb
    depends_on:
      - fake-s3
    environment:
      DEFAULT_REGION: eu-west-1
      AWS_ACCESS_KEY_ID: testkey
      AWS_SECRET_ACCESS_KEY: testsecret
      WHITELIST_BUCKET: s3://whitelist-bucket
      CERT_STORE_BUCKET: s3://certs-bucket
      ENDPOINT_URL: "http://fake-s3:4572"
    volumes:
      - raddb-certs:/etc/raddb/certs

  authentication-api-local:
    build:
      context: .authentication-api
      args:
        BUNDLE_INSTALL_CMD: bundle install --without test --no-cache --jobs 8
    depends_on:
      - user-details-db
    environment:
      DB_HOSTNAME: user-details-db
      DB_USER: root
      DB_PASS: testpassword
      DB_NAME: govwifi_local

  logging-api-local:
    build:
      context: .logging-api
      args:
        BUNDLE_INSTALL_CMD: bundle install --without test --no-cache --jobs 8
    depends_on:
      - sessions-db
    environment:
      DB_HOSTNAME: sessions-db
      DB_USER: root
      DB_PASS: testpassword
      DB_NAME: govwifi_local
      USER_DB_NAME: govwifi_local
      USER_DB_PASS: testpassword
      USER_DB_USER: root
      USER_DB_HOSTNAME: user-details-db

  test:
    build:
      context: acceptance_tests
    depends_on:
      - sessions-db
      - frontend-local
    environment:
      DB_HOSTNAME: sessions-db
      DB_NAME: govwifi_local
      DB_USER: root
      DB_PASS: testpassword
      USER_DB_NAME: govwifi_local
      USER_DB_PASS: testpassword
      USER_DB_USER: root
      USER_DB_HOSTNAME: user-details-db
      FRONTEND_CONTAINER: frontend-local
      RADIUS_KEY: testingradiussecret

volumes:
  raddb-certs:
