---
platform: linux

inputs:
  - name: src
  - name: frontend
  - name: authentication-api
  - name: logging-api

params:
  ON_CONCOURSE: true

run:
  path: docker-wrapper
  args: [src/ci/tasks/scripts/test.sh]
