version: 1
update_configs:
  - package_manager: "ruby:bundler"
    directory: "/acceptance_tests"
    update_schedule: "live"

  - package_manager: "docker"
    directory: "/fake-s3"
    update_schedule: "daily"

  - package_manager: "docker"
    directory: "/acceptance_tests"
    update_schedule: "daily"
